apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
  labels:
    app: backend-deploy
spec:
  selector:
    matchLabels:
      app: backend-pod
  template:
    metadata:
      name: backend-pod
      labels:
        app: backend-pod
    spec:
      readinessProbe:
        httpGet:
          scheme: HTTP
          path: /backend/goals
          port: 80
        initialDelaySeconds: 10
        periodSeconds: 5
      livenessProbe:
        httpGet:
          scheme: HTTP
          path: /backend/goals
          port: 80
        initialDelaySeconds: 12
        periodSeconds: 3
        failureThreshold: 2
      containers:
        - name: backend-pod
          image: abuzarmadki09/devops-project-2-backend
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: backend-db-con-creds
  replicas: 2
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend-service
spec:
  type: ClusterIP
  ports:
    - name: back-svc-prt
      targetPort: 80
      port: 80
  selector:
    app: backend-pod
