apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
  labels:
    app: fontend-deploy
spec:
  readinessProbe:
    httpGet:
      scheme: HTTP
      path: /
      port: 80
    initialDelaySeconds: 10
    periodSeconds: 5
  livenessProbe:
    httpGet:
      scheme: HTTP
      path: /
      port: 80
    initialDelaySeconds: 3
    periodSeconds: 3
    failureThreshold: 2
  selector:
    matchLabels:
      app: frontend-pod
  template:
    metadata:
      name: frontend-pod
      labels:
        app: frontend-pod
    spec:
      containers:
        - name: frontend-pod
          image: abuzarmadki09/devops-project-2-frontend
          ports:
            - containerPort: 3000
  replicas: 2
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend-service
spec:
  type: ClusterIP
  ports:
    - name: front-svc-prt
      targetPort: 3000
      port: 80
  selector:
    app: frontend-pod
